import xml.etree.ElementTree as ET

data = '''<?xml version="1.0" encoding="UTF-8"?>
<commentinfo>
  <note>This file contains the actual data for your assignment - good luck!</note>

  <comments>
    <comment>
       <name>Zuriel</name>
       <count>99</count>
    </comment>
    <comment>
       <name>Davie</name>
       <count>98</count>
    </comment>
    <comment>
       <name>Evangelina</name>
       <count>97</count>
    </comment>
    <comment>
       <name>Mehreen</name>
       <count>97</count>
    </comment>
    <comment>
       <name>Deegan</name>
       <count>96</count>
    </comment>
    <comment>
       <name>Zoe</name>
       <count>93</count>
    </comment>
    <comment>
       <name>Esteban</name>
       <count>91</count>
    </comment>
    <comment>
       <name>Pacey</name>
       <count>90</count>
    </comment>
    <comment>
       <name>Debbie</name>
       <count>88</count>
    </comment>
    <comment>
       <name>Laia</name>
       <count>87</count>
    </comment>
    <comment>
       <name>Luiza</name>
       <count>85</count>
    </comment>
    <comment>
       <name>Beatrice</name>
       <count>77</count>
    </comment>
    <comment>
       <name>Katrina</name>
       <count>75</count>
    </comment>
    <comment>
       <name>Osesenagha</name>
       <count>73</count>
    </comment>
    <comment>
       <name>Leevi</name>
       <count>72</count>
    </comment>
    <comment>
       <name>Stanley</name>
       <count>71</count>
    </comment>
    <comment>
       <name>Conrad</name>
       <count>67</count>
    </comment>
    <comment>
       <name>Shakeira</name>
       <count>67</count>
    </comment>
    <comment>
       <name>Tasnim</name>
       <count>64</count>
    </comment>
    <comment>
       <name>CJ</name>
       <count>62</count>
    </comment>
    <comment>
       <name>Lennix</name>
       <count>57</count>
    </comment>
    <comment>
       <name>Zhi</name>
       <count>55</count>
    </comment>
    <comment>
       <name>Ainslie</name>
       <count>55</count>
    </comment>
    <comment>
       <name>Oliwier</name>
       <count>46</count>
    </comment>
    <comment>
       <name>Katherine</name>
       <count>45</count>
    </comment>
    <comment>
       <name>Nicole</name>
       <count>42</count>
    </comment>
    <comment>
       <name>Kaisha</name>
       <count>42</count>
    </comment>
    <comment>
       <name>Pauline</name>
       <count>42</count>
    </comment>
    <comment>
       <name>Tristain</name>
       <count>39</count>
    </comment>
    <comment>
       <name>Angel</name>
       <count>38</count>
    </comment>
    <comment>
       <name>Maisha</name>
       <count>37</count>
    </comment>
    <comment>
       <name>Diarmid</name>
       <count>37</count>
    </comment>
    <comment>
       <name>Azedine</name>
       <count>36</count>
    </comment>
    <comment>
       <name>Fionnah</name>
       <count>36</count>
    </comment>
    <comment>
       <name>Micall</name>
       <count>33</count>
    </comment>
    <comment>
       <name>Latifa</name>
       <count>33</count>
    </comment>
    <comment>
       <name>Shanice</name>
       <count>32</count>
    </comment>
    <comment>
       <name>Guillaume</name>
       <count>29</count>
    </comment>
    <comment>
       <name>Olaoluwapolorimi</name>
       <count>28</count>
    </comment>
    <comment>
       <name>Caidy</name>
       <count>27</count>
    </comment>
    <comment>
       <name>Imani</name>
       <count>26</count>
    </comment>
    <comment>
       <name>Zaineddine</name>
       <count>24</count>
    </comment>
    <comment>
       <name>Jock</name>
       <count>20</count>
    </comment>
    <comment>
       <name>Tianna</name>
       <count>19</count>
    </comment>
    <comment>
       <name>Spondon</name>
       <count>15</count>
    </comment>
    <comment>
       <name>Remigiusz</name>
       <count>14</count>
    </comment>
    <comment>
       <name>Rebecca</name>
       <count>13</count>
    </comment>
    <comment>
       <name>Maaz</name>
       <count>10</count>
    </comment>
    <comment>
       <name>Tyla</name>
       <count>9</count>
    </comment>
    <comment>
       <name>Kellen</name>
       <count>4</count>
    </comment>
  </comments>
</commentinfo>'''
# print(data)
count = 0

# tree = ET.fromstring(data)
# x = tree.findall('.//count')

stuff = ET.fromstring(data)
lst = stuff.findall('.//count')
print(lst)

# for n in lst:
#     number = int(n)
#     count = count + number
# print('Sum: ',count)